### ISSUE TITLE
/> tags break the system

### ISSUE THREAD

**Issue by tommymchugh** [InclusiveTechNU/bri11iant#15]
```html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <img src="apple.jpg" />
    </body>
</html>
```

Versus
```html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <img src="apple.jpg">
    </body>
</html>
```

The first one seems to not be able to figure out where the img source is in the file and results in alerting the alt text warning at the <html> tag.

**Comment by cooperbarth** [comment]
I kinda just want to yell at people for not using HTML5 conventions if they do this :/

**Comment by cooperbarth** [comment]
Also, it's still able to find the src for these tags - there's some other parsing error causing the incorrect marking here.

**Comment by cooperbarth** [comment]
Fixed in https://github.com/InclusiveTechNU/bri11iant/commit/cd046601a1ac9ad52302d5584a05557918476299
